# Generated by Django 4.2.3 on 2023-11-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_hospital_password_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='availableBeds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
