# Generated by Django 4.2.3 on 2023-11-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_hospital_availablebeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='bedType',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='availableBeds',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='totalBeds',
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(choices=[('ICU', 'ICU'), ('GEN', 'General'), ('PRI', 'Private')], default='GEN', max_length=50),
        ),
        migrations.AlterField(
            model_name='bed',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospital_app.hospital'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Occupied'), (3, 'Maintenance')], default=1),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital_app.bed'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
