# Generated by Django 4.2.3 on 2023-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_remove_bed_bedtype_remove_hospital_availablebeds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='area',
            field=models.TextField(null=True),
        ),
    ]
